apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat-deployment
spec:
  selector:
    matchLabels:
      app: tomcat
  replicas: 1
  template:
    metadata:
      labels:
        app: tomcat
    spec:
      containers:
      - name: tomcatprodweb
        image: "imthiyazpalapra/dockerpoc:58"
        env:
        - name: "PORT"
          value: "8080"
